#!/usr/bin/env bash
# From sponja23/fzf-calibre

calibredb list --for-machine calibredb list --fields title,authors,formats |
    jq -cr '.[] | "\(.title) - \(.authors)\u001f\(.formats[0])"' |
    fzf -- \
        --prompt="Calibre> " \
        -d'\x1f' \
        --with-nth=1 |
    cut -d $'\x1f' -f 2 |
    tr '\n' '\0' |
    (xargs -0r xdg-open >/dev/null 2>&1 &)
