#!/bin/bash

all_boards="$(udevadm info /dev/input/event* | awk -v RS= "/E: ID_INPUT_KEYBOARD=1\n/" ORS="\n\n" | grep 'E: DEVNAME=.*' | sed 's/E: DEVNAME=\(.*\)/\1/')"

killall kmonad

for i in $all_boards; do
    echo "found $i"
    KBD_DEV="$i"
    export KBD_DEV
    KBDCFG=$(envsubst <~/.config/kmonad/default.kbd)
    kmonad <(echo "$KBDCFG") >/dev/null &
done

exit 0
