#!/usr/bin/env bash
# Clean music directory prior to tagging and sorting

shopt -s globstar

if [ "$1" = "-s" ] || [ "$1" = "--stream" ]; then
    stream=true
fi

# remove all whitespace and single quotes from names
find ./ -name '* *' -execdir perl-rename 's/ //g' {} +
find ./ -name '*'\''*' -execdir perl-rename 's/'\''//g' {} +

# move art folder
mv -i Artwork/ art/
mv -i Scans/ art/
mv -i Scan/ art/
mv -i Covers/ art/

# make directories
if ! [ "$stream" = "true" ]; then
    mkdir other
    mkdir source
    mkdir art
fi

# move files
find ./ -iname "disc\.cue" -exec mv -i {} other/disc.cue \;
find ./ -iregex ".*\.url$" -exec mv -i {} source/source.url \;
find ./ -iregex ".*\.torrent$" -exec mv -i {} source/source.torrent \;
find ./ -iregex ".*\.accurip$" -exec mv -i {} other/disc.accurip \;
find ./ -iname "front.jpg" -exec mv -i {} art/front.jpg \;
find ./ -iname "front.png" -exec mv -i {} art/front.png \;
find ./ -iregex ".*\.jpg" -exec mv -i {} art/ \;
find ./ -iregex ".*\.jpeg" -exec mv -i {} art/ \;
find ./ -iregex ".*\.png" -exec mv -i {} art/ \;
find ./ -iname "info.txt" -exec mv -i {} other/info.txt \;
find ./ -iregex ".*\.m3u$" -delete

# sort logs
for i in **/*.log; do
    if rg -e "AUDIOCHECKER" "$i"; then
        mv -i "$i" other/XLD.log
    elif rg -e "EAC extraction logfile" "$i" || rg -e "Exact Audio Copy" "$i"; then
        mv -i "$i" other/EAC.log
    elif rg -e "X Lossless Decoder" "$i"; then
        mv -i "$i" other/XLD.log
    elif rg -e "auCDtect" "$i"; then
        mv -i "$i" other/auCDtect.log
    fi
done

# sort txts
for i in **/*.txt; do
    if rg -e "auCDtect" "$i"; then
        mv -i "$i" other/auCDtect.txt
    else
        mv -i "$i" other/info.txt
    fi
done

# remove empty folders
find . -type d -empty -delete
