#!/bin/sh
# Sort music files tagged by picards
# set $file
file="$1"

sanitise()
{
    echo "$1" | sed -z 's/\n/, /g;s/, $/\n/;s/\//-/g;s/^0*//g'
}

# get tags from flac
if file "$file" | grep -e "FLAC audio"; then
    ext="flac"
    albumartist=$(sanitise "$(metaflac --show-tag=ALBUMARTIST --no-utf8-convert "$file" | sed 's/^ALBUMARTIST=//I')")
    echo "albumartist: $albumartist"
    album=$(sanitise "$(metaflac --show-tag=ALBUM --no-utf8-convert "$file" | sed 's/^ALBUM=//I')")
    echo "album: $album"
    title=$(sanitise "$(metaflac --show-tag=TITLE --no-utf8-convert "$file" | sed 's/^TITLE=//I')")
    echo "title: $title"
    year=$(sanitise "$(metaflac --show-tag=DATE --no-utf8-convert "$file" | sed -e 's/^DATE=//I' -e 's/\([0-9]\{4\}\).*/\1/')")
    echo "year: $year"
    oriyear=$(sanitise "$(metaflac --show-tag=ORIGINALDATE --no-utf8-convert "$file" | sed -e 's/^ORIGINALDATE=//I' -e 's/\([0-9]\{4\}\).*/\1/')")
    echo "oriyear: $oriyear"
    media=$(sanitise "$(metaflac --show-tag=MEDIA --no-utf8-convert "$file" | sed 's/^MEDIA=//I')")
    echo "media: $media"
    label=$(sanitise "$(metaflac --show-tag=LABEL --no-utf8-convert "$file" | sed 's/^LABEL=//I')")
    if [ -z "$label" ]; then
        label=$(sanitise "$(metaflac --show-tag=ORGANIZATION --no-utf8-convert "$file" | sed 's/^ORGANIZATION=//I')")
    fi
    echo "label: $label"
    catalog=$(sanitise "$(metaflac --show-tag=CATALOGNUMBER --no-utf8-convert "$file" | sed 's/^CATALOGNUMBER=//I')")
    echo "catalog: $catalog"
    source=$(sanitise "$(metaflac --show-tag=SOURCE --no-utf8-convert "$file" | sed 's/^SOURCE=//I')")
    echo "source: $source"
    disc=$(sanitise "$(metaflac --show-tag=DISCNUMBER --no-utf8-convert "$file" | sed 's/^DISCNUMBER=//I')")
    echo "disc: $disc"
    tdiscs=$(sanitise "$(metaflac --show-tag=TOTALDISCS --no-utf8-convert "$file" | sed 's/^TOTALDISCS=//I')")
    if [ -z "$tdiscs" ]; then
        tdiscs=$(sanitise "$(metaflac --show-tag=DISCTOTAL --no-utf8-convert "$file" | sed 's/^DISCTOTAL=//I')")
    fi
    echo "tdiscs: $tdiscs"
    discsub=$(sanitise "$(metaflac --show-tag=DISCSUBTITLE --no-utf8-convert "$file" | sed 's/^DISCSUBTITLE=//I')")
    echo "discsub: $discsub"
    track=$(sanitise "$(metaflac --show-tag=TRACKNUMBER --no-utf8-convert "$file" | sed 's/^TRACKNUMBER=//I')")
    echo "track: $track"
    ttracks=$(sanitise "$(metaflac --show-tag=TOTALTRACKS --no-utf8-convert "$file" | sed 's/^TOTALTRACKS=//I')")
    if [ -z "$ttracks" ]; then
        ttracks=$(sanitise "$(metaflac --show-tag=TRACKTOTAL --no-utf8-convert "$file" | sed 's/^TRACKTOTAL=//I')")
    fi
    echo "ttracks: $ttracks"
fi


# get tags from mp3
if ffprobe "$file" 2>&1 | grep -e "Audio: mp3"; then
    ext="mp3"
    metadata="$(ffprobe "$file" 2>&1)"
    albumartist="$(echo "$metadata" | grep "^ \+album_artist \+: " | sed 's/^ \+album_artist \+: //')"
    #echo "albumartist: $albumartist"
    album="$(echo "$metadata" | grep "^ \+album \+: " | sed 's/^ \+album \+: //')"
    #echo "album: $album"
    title="$(echo "$metadata" | grep "^ \+title \+: " | sed 's/^ \+title \+: //')"
    #echo "title: $title"
    year="$(echo "$metadata" | grep "^ \+date \+: " | sed -e 's/^ \+date \+: //' -e 's/\([0-9]\{4\}\).*/\1/')"
    #echo "year: $year"
    oriyear="$(echo "$metadata" | grep "^ \+originalyear \+: " | sed -e 's/^ \+originalyear \+: //' -e 's/\([0-9]\{4\}\).*/\1/')"
    #echo "oriyear: $oriyear"
    media="$(echo "$metadata" | grep "^ \+TMED \+: " | sed 's/^ \+TMED \+: //')"
    #echo "media: $media"
    label="$(echo "$metadata" | grep "^ \+publisher \+: " | sed 's/^ \+publisher \+: //')"
    #echo "label: $label"
    catalog="$(echo "$metadata" | grep "^ \+CATALOGNUMBER \+: " | sed 's/^ \+CATALOGNUMBER \+: //')"
    #echo "catalog: $catalog"
    source="$(echo "$metadata" | grep -i "^ \+source \+: " | sed 's/^ \+source \+: //I')"
    #echo "source: $source"
    disc="$(echo "$metadata" | grep "^ \+disc \+: " | sed 's/^ \+disc \+: \([0-9]\+\)\/.*/\1/')"
    #echo "disc: $disc"
    tdiscs="$(echo "$metadata" | grep "^ \+disc \+: " | sed 's/^ \+disc \+: [0-9]\+\/\([0-9]\+\).*/\1/')"
    #echo "totaldiscs: $tdiscs"
    # TODO: use correct subtitle tag
    discsub="$(echo "$metadata" | grep "^ \+subtitle \+: " | sed 's/^ \+subtitle \+: //')"
    #echo "discsub: $discsub"
    track="$(echo "$metadata" | grep "^ \+track \+: " | sed 's/^ \+track \+: \([0-9]\+\)\/.*/\1/')"
    #echo "disc: $disc"
    ttracks="$(echo "$metadata" | grep "^ \+track \+: " | sed 's/^ \+track \+: [0-9]\+\/\([0-9]\+\).*/\1/')"
    #echo "tracks: $ttracks"
fi

# get tags from dsf
if ffprobe "$file" 2>&1 | grep -e "Audio: dsd_lsbf_planar"; then
    ext="dsf"
    metadata="$(ffprobe "$file" 2>&1)"
    if echo "$metadata" | grep -e 'Audio: dsd_lsbf_planar, [0-9]\+ Hz, 5.1, .*'; then
        channels="5.1"
    elif echo "$metadata" | grep -e 'Audio: dsd_lsbf_planar, [0-9]\+ Hz, stereo, .*'; then
        channels="2"
    fi
    echo $channels
    albumartist="$(sanitise "$(echo "$metadata" | grep "^ \+album_artist \+: " | sed 's/^ \+album_artist \+: //')")"
    echo "albumartist: $albumartist"
    album="$(sanitise "$(echo "$metadata" | grep "^ \+album \+: " | sed 's/^ \+album \+: //')")"
    echo "album: $album"
    title="$(sanitise "$(echo "$metadata" | grep "^ \+title \+: " | sed 's/^ \+title \+: //')")"
    echo "title: $title"
    year="$(sanitise "$(echo "$metadata" | grep "^ \+date \+: " | sed -e 's/^ \+date \+: //' -e 's/\([0-9]\{4\}\).*/\1/')")"
    echo "year: $year"
    oriyear="$(sanitise "$(echo "$metadata" | grep "^ \+originalyear \+: " | sed -e 's/^ \+originalyear \+: //' -e 's/\([0-9]\{4\}\).*/\1/')")"
    echo "oriyear: $oriyear"
    media="$(sanitise "$(echo "$metadata" | grep "^ \+TMED \+: " | sed -e 's/^ \+TMED \+: //' -e 's/ (.*)//')")"
    echo "media: $media"
    label="$(sanitise "$(echo "$metadata" | grep "^ \+publisher \+: " | sed 's/^ \+publisher \+: //')")"
    echo "label: $label"
    catalog="$(sanitise "$(echo "$metadata" | grep "^ \+CATALOGNUMBER \+: " | sed 's/^ \+CATALOGNUMBER \+: //')")"
    echo "catalog: $catalog"
    source="$(sanitise "$(echo "$metadata" | grep -i "^ \+source \+: " | sed 's/^ \+source \+: //I')")"
    echo "source: $source"
    disc="$(sanitise "$(echo "$metadata" | grep "^ \+disc \+: " | sed 's/^ \+disc \+: \([0-9]\+\)\/.*/\1/')")"
    echo "disc: $disc"
    tdiscs="$(sanitise "$(echo "$metadata" | grep "^ \+disc \+: " | sed 's/^ \+disc \+: [0-9]\+\/\([0-9]\+\).*/\1/')")"
    echo "totaldiscs: $tdiscs"
    #TODO: use correct subtitle tag
    discsub="$(sanitise "$(echo "$metadata" | grep "^ \+subtitle \+: " | sed 's/^ \+subtitle \+: //')")"
    echo "discsub: $discsub"
    track="$(sanitise "$(echo "$metadata" | grep "^ \+track \+: " | sed 's/^ \+track \+: \([0-9]\+\)\/.*/\1/')")"
    echo "disc: $disc"
    ttracks="$(sanitise "$(echo "$metadata" | grep "^ \+track \+: " | sed 's/^ \+track \+: [0-9]\+\/\([0-9]\+\).*/\1/')")"
    echo "tracks: $ttracks"
fi

# set $multidisc
if [ "$tdiscs" = "1" ]; then
    multidisc="false"
elif [ "$tdiscs" ]; then
    multidisc="true"
else
    echo "no totaldiscs tag found"
    multidisc="true" # in case the release is multidisc to preserve directories
fi

# set $printtrack
if [ "$multidisc" = "true" ]; then
    printtrack="$disc-$(printf %02d "$track")"
else
    printtrack="$(printf %02d "$track")"
fi

# set discfolder
if [ "$multidisc" = "false" ]; then
    discdir=""
elif [ "$discsub" ]; then
    discdir="disc $disc - $discsub"
else
    discdir="disc $disc"
fi

discdir="$(echo "$discdir" | sed 's/\//-/')""/"

# set filename
filename="$(echo "$printtrack $title.$ext" | sed 's/\//-/')"
if [ "$channels" = "5.1" ]; then
    filename="[5.1] $filename"
fi

# set $useyear
if [ "$year" ] && [ "$oriyear" ]; then
    if  [ "$year" = "$oriyear" ]; then
        useyear="year"
    else
        useyear="both"
    fi
elif [ "$year" ]; then
    useyear="year"
elif [ "$oriyear" ]; then
    useyear="oriyear"
else
    echo "no year tags found"
    exit
fi

# set $printyear
if [ "$useyear" = "year" ]; then
    printyear="$year"
elif [ "$useyear" = "oriyear" ]; then
    printyear="$oriyear"
elif [ "$useyear" = "both" ]; then
    printyear="$oriyear""-""$year"
fi

# set folder
albumdir="$(echo "($printyear) $album ($label - $catalog) [$media - $source]" | sed 's/\//-/')""/"

# set artistfolder
artistdir="$(echo "$albumartist" | sed 's/\//-/')""/"

# do the move
parent="$(dirname "$file")"
mvroot="$HOME/Music/"
mvdir="$mvroot""$artistdir""$albumdir""$discdir"
mkdir -p "$mvdir"
mv -i "$file" "$mvdir""$filename"
cd "$parent" || exit
find ./ -maxdepth 1 -regex './.+' | sed -e '/\.flac$/d' -e '/\.mp3$/d' -e '/\.dsf$/d'| xargs -I '{}' mv '{}' "$mvdir"
cd ..
find "$parent" -depth -type d -exec rm -d {} \;
