#!/bin/env bash
# Change wallapaper with hsetroot

usage="usage: pape <file> [--interactive]"
papeconf=~/.config/rice/pape
# xrandrconf=~/.config/arandr.sh
# display="$(grep -Po "[A-Z0-9\-]+(?= --primary)" $xrandrconf)"

if [ "$2" ]; then
    papedir="$2"
else
    papedir="$(pwd)"
fi

if [ "$1" = "--interactive" ] || [ "$1" = "-i" ]; then
    prompt="1"
elif [ "$1" = "--solid" ] || [ "$1" = "-s" ]; then
    if [ "$2" ]; then
        configured="$2"
    else
        configured="$(xrdb -query | grep '^\*background' | cut -f 2)"
    fi
elif [ "$1" = "--riced" ] || [ "$1" = "-r" ]; then
    configured="$(cat $papeconf)"
elif [ "$1" ]; then
    configured="$1"
else
    echo "$usage"
    exit
fi

if [ "$prompt" = "1" ]; then
    if [ -f "$(which fzfimg.sh)" ]; then
        configured="$(find "$papedir" -type f | fzfimg.sh | xargs -0 readlink -f)"
    elif [ -f "$(which fzf-ueberzogen.sh)" ]; then
        configured="$(find "$papedir" -type f | fzf-ueberzogen.sh | xargs -0 readlink -f)"
    else
        configured="$(find "$papedir" -type f | fzf | xargs -0 readlink -f)"
    fi
fi

if [[ -f "$configured" ]]; then

        # Determine size
        sz="$(exiv2 "$configured" 2>/dev/null | grep "^Image size" | cut -f 2 -d ':' | cut -f 2 -d ' ')"
        if [ "$sz" -gt "1000" ]; then
            hsetroot -fill "$configured"
        else
            hsetroot -tile "$configured"
        fi
elif [ -n "$(echo "$configured" | grep "^#")" ]; then
    hsetroot -solid "$configured"
else
    echo "$configured not found"
    exit
fi
echo "$configured" > $papeconf
