#!/bin/sh
# Get neccessary files for bootstrap script

if [ "$1" ]; then
    outdir="$1"
else
    outdir="$(pwd)/bootstrap"
fi

mkdir -p "$outdir"/gpg
mkdir -p "$outdir"/.ssh

gpg --export-secret-keys --armor --output "$outdir"/gpg/key.asc
gpg --export-ownertrust >"$outdir"/gpg/ownertrust.txt

cp ~/.ssh/strap_rsa.pub "$outdir"/.ssh
cp ~/.ssh/strap_rsa "$outdir"/.ssh

cd ~/git/scripts/ || exit
git pull
cp strap "$outdir"
