#!/bin/sh
# Bootstrap system after fresh Arch install
# Note: first set up user account to run script

sudo pacman -Syu base-devel zsh gnupg openssh git yadm networkmanager perl
git clone https://aur.archlinux.org/yay.git yay/
cd yay/ || exit
makepkg -si
cd ~ || exit
rm -rf yay/

# Networking

sudo systemctl enable NetworkManager

# Import GPG keys

mkdir -p ~/.local/share/gnupg
export GNUPGHOME=~/.local/share/gnupg/

find . -name '*.key' -exec gpg --allow-secret-key-import --import {} \;
find . -name '*.asc' -exec gpg --allow-secret-key-import --import {} \;
find . -name 'pubring.kbx' -exec gpg --import {} \;
find . -name '*ownertrust.txt' -exec gpg --import-ownertrust {} \;

# Add bootstrap key to ssh-agent

eval "$(ssh-agent -s)"
ssh-add ~/.ssh/strap_rsa

# Clone repos

yadm clone git@gitlab.com:liamvdvyver/dotfiles-public.git

mkdir ~/git/
git clone git@gitlab.com:liamvdvyver/scripts.git ~/git/scripts/
git clone git@gitlab.com:liamvdvyver/dotfiles-secret.git ~/git/dotfiles-secret/
git clone git@gitlab.com:liamvdvyver/password-store.git ~/git/password-store/

# Set shell to ZSH

chsh -s /bin/zsh

# Reboot

cat /etc/pacman.conf > pacman.conf.bak
cat /etc/pacman.conf | perl -0pe 's/#\[multilib\]\n#Include/[multilib]\nInclude/' | sed 's/^#\(ParallelDownloads.*\)/\1/' | sudo tee /etc/pacman.conf
echo "strap_2" >> ~/.config/zsh/.zshrc
sudo reboot now
