#!/bin/sh
# Restore zshrc after reboot

sed -i "/^strap_2$/d" ~/.config/zsh/.zshrc

# Decrypt secrets

crypt -d

# Make sure to install linux (-firmare -headers) base (-devel) networkmanager
sudo pacman -Sy
yay -S --norebuild --noredownload \
    xorg-server xorg-xinit xorg-xrandr xorg-xsetroot xorg-xinput xorg-xkill \
    xorg-xev xorg-xwininfo \
    xclip xwallpaper xdotool xdg-user-dirs \
    i3-gaps i3lock i3status \
    dmenu sxhkd flameshot dunst pass network-manager-applet \
    gnome-themes-extra noto-fonts ttf-hack-nerd papirus-icon-theme gruvbox-icon-theme \
    picom-tryone-git hsetroot qt5-styleplugins ueberzug \
    arandr lxappearance \
    xterm kitty \
    pulseaudio pulseaudio-alsa lib32-libpulse pavucontrol \
    qutebrowser pdfjs-legacy brave-bin lynx \
    pcmanfm mpv sxiv zathura zathura-pdf-mupdf sxiv \
    exa man-db man-pages ripgrep wget \
    fd fzf tmux ranger dragon-drop \
    htop btop ncmpcpp newsboat mutt-wizard \
    mpd mpdris2 spotifyd spotify-tui-bin playerctl \
    perl-anyevent-i3 perl-image-exiftool perl-rename \
    r rstudio-desktop-bin gcc-fortran \
    python python-pip python-adblock \
    zsh-autosuggestions zsh-sudo-git zsh-syntax-highlighting \
    zsh-you-should-use \
    bash-complete-alias bash-completion \
    cowsay figlet fortune-mod lolcat neofetch pfetch unimatrix-git \
    texlive-most biber \
    ytfzfim yt-dlp \
    handbrake jellyfin-bin makemkv \
    cuetools exact-audio-copy ffmpeg foobar2000 losslessaudiochecker mp3info \
    picard puddletag quodlibet sacd-extract \
    nicotine+ qbittorrent \
    android-file-transfer ntfs-3g \
    bridge-utils dnsmasq iptables-nft libvirt qemu-desktop vde2 virt-manager \
    calibre joplin-desktop libreoffice-still zoom \
    ledger-live-bin monero \
    nano neovim shellcheck shfmt ctags \
    cups epson-inkjet-printer-escpr \
    darktable gimp \
    barrier calibre rclone smartmontools wine-mono jdownloader2 discord unrar

pip install rtv pynvim

mkdir -p ~/.local/lib/R
Rscript -e "install.packages(c('languageserver', 'stringi', 'pacman'))"

# Configure ranger

ranger --copy-config=scope
git clone https://github.com/alexanderjeurissen/ranger_devicons ~/.config/ranger/plugins/ranger_devicons

# Configure nvim

nvim --headless +PlugInstall +CocInstall +qa

# Google drive

rclone sync Drive: ~/drive

# KVM

sudo systemctl enable libvirtd
uname=$(whoami)
sudo usermod -aG libvirt "$uname"
cp /etc/libvirt/libvirtd.conf ~/libvirtd.conf.bak
sudo sed -i 's/#\(unix_sock_group = .libvirt.\)/\1/;s/#\(unix_sock_rw_perms = .0770.\)/\1/' /etc/libvirt/libvirtd.conf
cp /etc/libvirt/qemu.conf ~/qemu.conf.bak
sudo sed -i "s/#user = \"libvirt-qemu\"/user = $uname/;s/#group = \"libvirt-qemu\"/group = $uname/" /etc/libvirt/qemu.conf

# Directories (generate and clean)

xdg-user-dirs-update
rm .bash_history
rm .bash_profile
rm .bash_logout
rm gpg_keys
rm pacman.conf.bak

# Fin

echo "Bootstrap completed."
echo "Install graphics drivers and reboot to complete setup."
read -p "Press enter to exit."
