#!/bin/sh

shutdown="󰐥 shut down"
lock="󰌾 lock"
reboot="󰜉 reboot"
exit="󰈆 exit"
suspend="󰤄 suspend"

selected="$( (echo "$suspend" && echo "$lock" && echo "$exit" && echo "$shutdown" && echo "$reboot") | dmenu)"

case $selected in
    "")
        exit 0
       ;;
    "$lock")
        i3lock -c 000000
        ;;
    "$suspend")
        i3lock -c 000000 && systemctl suspend
        ;;
    "$shutdown")
        shutdown now
        ;;
    "$exit")
        i3 exit
        ;;
    "$reboot")
        reboot
        ;;
    *)
        echo "No match"
        exit 1
        ;;
esac
