#!/usr/bin/env sh

shutdown="󰐥 shut down"
lock="󰌾 lock"
reboot="󰜉 reboot"
exit="󰈆 exit"
suspend="󰤄 suspend"
hibernate=" hibernate"

selected="$( (echo "$suspend" && echo "$lock" && echo "$hibernate" && echo "$exit" && echo "$shutdown" && echo "$reboot") | dmenu)"

exit_wm() {
    i3 exit
    xwmux-ctl exit
}

case $selected in
    "")
        exit 0
       ;;
    "$lock")
        i3lock -c 000000
        ;;
    "$suspend")
        i3lock -c 000000 && systemctl suspend
        ;;
    "$shutdown")
        shutdown now
        ;;
    "$exit")
        exit_wm
        ;;
    "$reboot")
        reboot
        ;;
    "$hibernate")
        i3lock -c 000000 && systemctl hibernate
        ;;
    *)
        echo "No match"
        exit 1
        ;;
esac
