#!/usr/bin/env bash
# taken from github.com/ThePrimeagen/.dotfiles
# adapted to work with tmuxifier for custom layouts

default_command="tmuxifier load-window dev"
project_dir="$HOME/git/"

if [[ $# -eq 1 ]]; then
    selected=$1
else
    dirs=$(find "$project_dir" -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)
    sessions=$(tmux list-sessions | cut -d : -f 1)
    tmuxifiers=$(tmuxifier list-sessions)
    list=$(echo "$dirs" &&  echo "$sessions" && echo "$tmuxifiers")
    selected=$(echo "$list" | sort | uniq | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(echo "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -n $TMUX ]] || [[ -n $tmux_running ]]; then

    if tmux has-session -t="$selected_name" 2> /dev/null; then
        :

    elif tmuxifier list-sessions | grep -q "$selected"; then
        tmuxifier load-session "$selected"

    else
        target_dir="$project_dir""$selected"
        tmux new-session -ds "$selected_name" -c "$target_dir" "$default_command"

    fi
else

    if tmuxifier list-sessions | grep -q "$selected"; then
        tmuxifier load-session "$selected"

    else
        target_dir="$project_dir""$selected"
        tmux new-session -s "$selected_name" -c "$target_dir" "$default_command"

    fi
fi

tmux switch-client -t "$selected_name" 2> /dev/null || tmux at -t "$selected_name"
