#!/usr/bin/env bash
# taken from github.com/ThePrimeagen/.dotfiles

if [[ $# -eq 1 ]]; then
    selected=$1
else
    dirs=$(find ~/git -mindepth 1 -maxdepth 1 -type d)
    sessions=$(tmux list-sessions | cut -d : -f 1)
    custom=$(echo "$HOME/Documents/pkb ncspot scratchpad yadm school" | tr ' ' '\n')
    list=$(echo "$dirs" && echo "$custom" && echo "$sessions")
    selected=$(echo "$list" | sort | uniq | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

command="nvim"
selected_name=$(basename "$selected" | tr . _)
if [[ $selected_name = 'pkb' ]]; then
    selected_name="pkb"
    command="nvim index.md"
elif [[ $selected_name = 'ncspot' ]]; then
    selected=~
    command="ncspot"
elif [[ $selected_name = 'scratchpad' ]] || [[ $selected_name = 'school' ]]; then
    selected=~
    command=""
elif [[ $selected_name = 'yadm' ]]; then
    selected=~
    command="yadm enter nvim"
fi
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c "$selected" $command
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c "$selected" $command
fi

tmux switch-client -t $selected_name 2> /dev/null || tmux at -t $selected_name
