#!/usr/bin/env bash
# Credit to github.com/stefanv

shopt -s nullglob globstar

typeit=0
regex=".*"
while [[ -n "$1" ]]; do
    if [[ $1 == "--type" || $1 -- "-t" ]]; then
        typeit=1
        shift
    elif [[ $1 == "--user" || $1 == "-u" ]]; then
        regex='user(name)?: \K.*'
        echo woo
        shift
    fi
done

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password=$(cd "$prefix" && find -- * -type f -iname "*.gpg" -exec sh -c 'printf "%s\n" "${@%.gpg}"' _ {} + | dmenu -i "$@")

[[ -n $password ]] || exit

result=$(pass show "$password" | grep -o -P "$regex" | head -n 1)

if [[ $typeit -eq 0 ]]; then
    echo $result | xclip  # send to middle button paste
else
    xdotool type $result # type
fi
